name: "Update Assets"

on: [workflow_dispatch]

jobs:
  update:
    name: Update assets

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Setup CI Authentication
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Install NPM on Laravel Nova
        run: npm --prefix "./vendor/laravel/nova/" ci

      - name: Compile Asset
        run: |
          yarn install
          yarn run production
        env:
          TAILWIND_MODE: build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Assets
